import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
export default function Home() {
  return (
    <div   >
      <Head>
        <title>Best Online Food Delivery Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar className=""/>
      <main className="w-screen h-screen">
        <div className="1st bg-[url('../public/online_store/bg1.jpg')] absolute bg-no-repeat bg-cover w-full h-5/6 top-0 ">
      <div className="bg-1-inside-text flex flex-col py-1 px-64  justify-center align-middle text-center text-white" style={{height:'36rem'}}>
      <h1 className='text-4xl font-bold font-mono'>Welcome to my MyOnlineMeals</h1>
      <p className='text-xl font-semibold my-2' >Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eum doloribus debitis perferendis culpa corporis ipsa enim, possimus quia aliquam at doloremque minus id odit quos voluptatum eaque excepturi pariatur voluptas.</p>
      <button type="button" class=" mx-auto mt-5 w-28 inline-block px-6 py-2 border-2   border-white text-orange-900 font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 hover:border-orange-900 hover:text-white focus:outline-none focus:ring-0 transition duration-150 ease-in-out overflow-hidden " style={{backgroundColor:"red"}}>Primary</button>
    </div>
      </div>
   
    <div className="2nd  bg-white  justify-center relative top-96 mt-32 z-10 ">
      <h1 className=' font-bold text-5xl text-black text-center m-20'>Our Services</h1>
      <div className="flex flex-row space-x-10 justify-center">
        <div className="2nd_container_1  border-2 rela border-emerald-200 hover:border-emerald-300 p-2  rounded-lg" style={{width :"22.5rem" , height:"25rem"}}>
          <img src="./online_store/order1.png"   alt="not found img1" className='my-5 mx-auto w-52 h-40' />
          <h1 className='font-bold text-3xl text-center hover:text-orange-700  ' >Food Odering</h1>
          <p className='font-semibold text-base my-2 text-center ' >Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur, hic dolore. Doloribus nihil, quasi obcaecati exercitationem eos doloremque iusto veritatis minus praesentium aspernatur officia similique, quibusdam dolore  </p>
        </div>
        <div className="2nd_container_2 border-2 border-emerald-200 hover:border-emerald-300 rounded-lg p-2" style={{width :"22.5rem" , height:"25rem"}}>
          <img src="./online_store/order2.png" alt="not found img2"  className='my-5 mx-auto w-52 h-40'/>
          <h1 className='font-bold text-3xl text-center hover:text-orange-700  ' >Food Catering</h1>
          <p className='font-semibold text-base my-2 text-center ' >Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cum, eligendi cumque quibusdam earum maxime minima officiis. Quas sint quo, quibusdam, quisquam odio fugiat tempore adipisci rem </p>
        </div>
        <div className="2nd_container_3 border-2 border-emerald-200 hover:border-emerald-300 p-2  rounded-lg" style={{width :"22.5rem" , height:"25rem"}}>
        <img src="./online_store/order3.png" alt="not found img3"  className='my-5 mx-auto w-52 h-40'/>
          <h1 className='font-bold text-3xl text-center hover:text-orange-700  ' >Bulk Ordering</h1>
          <p className='font-semibold text-base my-2 text-center ' >Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio molestias architecto, ex exercitationem reprehenderit vel dignissimos iusto nostrum amet, praesentium mollitia facere dolorum. P delectus, iste ipsum!</p>
        </div>
      </div>
    </div>
    <div className="3rd relative top-2/3 w-screen h-60 bg-white justify-center z-10 text-center ">
        <h1 className='font-bold text-black text-4xl m-12'>Our Client</h1>
        <div className="client_img flex flex-row justify-center space-x-32">
          <img src="./online_store/logo1.png" className='w-32 h-36' alt="logo 1st" />
          <img src="./online_store/logo2.png" className='w-32 h-36' alt="logo 2st" />
          <img src="./online_store/logo3.png" className='w-32 h-36' alt="logo 3st" />
          <img src="./online_store/logo4.png" className='w-40 h-36' alt="logo 4st" />
        </div>
    </div>
     
     <div className=" my-4 Contact_us relative w-screen h-full top-2/3 z-10 bg-amber-900 bg-[url('../public/online_store/contact.jpg')] bg-no-repeat bg-cover">
       <form action="/" className='flex flex-col w-96 justify-center mx-auto   align-middle'>
        <h1 className='font-bold text-3xl text-center my-3'>Contact Us</h1>
        <label className='font-semibold text-lg'  htmlFor="Name">Name:</label>
        <input className='font-semibold text-lg rounded-xl border-2 border-zinc-400 hover:border-zinc-600' type="text" />
        <label className='font-semibold text-lg' htmlFor="Email">Email:</label>
        <input className='font-semibold text-lg  rounded-xl border-2 border-zinc-400 hover:border-zinc-600' type="email" />
        <label className='font-semibold text-lg' htmlFor="Phone Number">Phone Number:</label>
        <input className='font-semibold text-lg rounded-xl border-2 border-zinc-400 hover:border-zinc-600' type="number" name="phone Number" id="" />
        <label className='font-semibold text-lg' htmlFor="Message">Message:</label>
        <textarea className='font-semibold text-lg rounded-xl border-2 border-zinc-400 hover:border-zinc-600' name="Message" id="Message" cols="30" rows="10"></textarea>
        <button type="button" class=" mx-auto mt-5 w-28 inline-block px-6 py-2 border-2   border-white text-orange-900 font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 hover:border-orange-900 hover:text-white focus:outline-none focus:ring-0 transition duration-150 ease-in-out overflow-hidden " style={{backgroundColor:"red"}}>Submit</button>
       </form>
     </div>
      </main>

    <Footer className="relative" style={{top:'780px' }}/>
    </div>
  )
}
